# Use the official MySQL image as a base
FROM mysql:5.7

# Set environment variables (if needed)
# ENV MYSQL_DATABASE=my_database
# ENV MYSQL_USER=my_user
# ENV MYSQL_PASSWORD=my_password
# ENV MYSQL_ROOT_PASSWORD=my_root_password

# Copy custom configuration files (if needed)
# COPY my.cnf /etc/mysql/conf.d/
